[settings]
npm.package_manager = "npm"
python.uv_venv_auto = "create|source"
github.use_git_credentials = true


[tools]
node = "lts"
npm = "11.6.4"
python = "3.11"
java = "latest"
bun = "latest"
deno = "latest"
go = "latest"
erlang = "latest"
elixir = "latest"
terraform = "latest"
uv = "latest"
"github:longbridge/longbridge-terminal" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@anthropic-ai/sandbox-runtime" = "latest"
"npm:@augmentcode/auggie" = "latest"
"npm:@cloudbase/cli" = "latest"
"npm:@cloudbase/cloudbase-mcp" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@murongg/aah-cli" = "latest"
"npm:@musistudio/claude-code-router" = "latest"
"npm:@openai/codex" = "latest"
"npm:@tencent-ai/codebuddy-code" = "latest"
"npm:@tencent/claude-code-internal" = "latest"
"npm:@tencent/codex-internal" = "latest"
"npm:@yfme/weapp-dev-mcp" = "latest"
"npm:agent-browser" = "latest"
"npm:corepack" = "latest"
"npm:firebase-tools" = "latest"
"npm:fx" = "latest"
"npm:httpyac" = "latest"
"npm:mammoth" = "latest"
"npm:node-firestore-import-export" = "latest"
"npm:npm-check-updates" = "latest"
"npm:opencode-ai" = "latest"
"npm:sharp-cli" = "latest"
"npm:whistle" = "2.9.97"
"npm:yarn" = "latest"
"npm:pnpm" = "latest"

[env]
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }
