#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config window_shadow                on

yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  00
yabai -m config bottom_padding               00
yabai -m config left_padding                 00
yabai -m config right_padding                00
yabai -m config window_gap                   10

yabai -m rule --add app="^iStat*" sticky=on layer=above manage=off border=off
yabai -m rule --add app="^System Preferences*" manage=off