#!/bin/zsh


setup_omz() {
  echo "==========================================================="
  echo "                      Shells Enviroment"
  echo "-----------------------------------------------------------"
  echo "* Installing Oh-My-Zsh..."
  echo "-----------------------------------------------------------"

  mv -f ~/.oh-my-zsh ~/.oh-my-zsh.old

  curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash

  echo "-----------------------------------------------------------"
  echo "* Installing ZSH Custom Plugins & Themes:"
  echo ""
  echo "  - zsh-autosuggestions"
  echo "  - fast-syntax-highlighting"
  echo "  - p10k zsh-theme"
  echo "  - zsh-z"
  echo "  - fzf-tab"
  echo "-----------------------------------------------------------"

  git clone https://github.com/Aloxaf/fzf-tab ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom/}/plugins/fzf-tab
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting

  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
}

clear_existed_dot() {
    echo "-----------------------------------------------------------"
    echo "* Clear existed dotfile"
    echo "-----------------------------------------------------------"

    mv -f "$HOME/.bashrc" "$HOME/.bashrc.old" 
    mv -f "$HOME/.bash_profile" "$HOME/.bash_profile.old"
    mv -f "$HOME/.zshrc" "$HOME/.zshrc.old"
}

init_lkdots() {
    echo "-----------------------------------------------------------"
    echo "* Init lkdots"
    echo "-----------------------------------------------------------"

    cd "$HOME/dotfiles"
    lkdots
}

clone_repo() {
  echo "-----------------------------------------------------------"
  echo "* Cloning dotfiles Repo from GitHub.com"
  echo "-----------------------------------------------------------"

  if [ ! -d ~/dotfiles ]
  then
    git clone https://github.com/fengkx/dotfiles.git ~/dotfiles
  fi

  cd ~/dotfiles
}

install_dev_runtimes() {
  echo "==========================================================="
  echo "              Setting up Dev Runtime Environment"
  echo "-----------------------------------------------------------"
  echo "* Installing global runtime toolchain from mise..."
  echo "-----------------------------------------------------------"

  bash "$HOME/dotfiles/script/install-dev-runtimes.sh" "$HOME/dotfiles"
}

start() {
    clear
    echo "=================== Install DotFiles ================="
    setup_omz
    clear_existed_dot
    clone_repo
    init_lkdots
    source ~/.zshrc
    install_dev_runtimes
    echo "=================== Done ================="
}

start
