model = "gpt-5.4-mini"
model_reasoning_effort = "medium"
personality = "pragmatic"

sandbox_mode = "workspace-write"
approvals_reviewer = "user"
plan_mode_reasoning_effort = "high"

notify = [
    "/Users/fengkx/.codex/plugins/cache/openai-bundled/computer-use/1.0.758/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
    "turn-ended",
]

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"
startup_timeout_ms = 20_000


[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.weapp-devtool]
command = "npx"
args = ["@yfme/weapp-dev-mcp"]

[mcp_servers.weapp-devtool.tools.mp_ensureConnection]
approval_mode = "approve"


writeable_roots = [
    "/Users/fengkx/Library/pnpm/store",
    "/Users/fengkx/.cache/uv",
    "/Users/fengkx/.cache/clang/ModuleCache",
    "/Users/fengkx/Library/Caches/org.swift.swiftpm",
    "/Users/fengkx/Library/org.swift.swiftpm",
]

[projects."/Users/fengkx/me/code/macos-dictkit"]
trust_level = "trusted"

[projects."/Users/fengkx/genie-mp"]
trust_level = "trusted"

[projects."/Users/fengkx/me/code/dict-demo"]
trust_level = "trusted"

[projects."/Users/fengkx/mp-a"]
trust_level = "trusted"

[projects."/Users/fengkx/me/code/anki-mate"]
trust_level = "trusted"

[features]
multi_agent = true

[projects."/Users/fengkx/dotfiles"]
trust_level = "trusted"

[projects."/Users/fengkx/me/code/NodeRSSBot"]
trust_level = "trusted"

[tui]
status_line = [
    "model-with-reasoning",
    "current-dir",
    "project-root",
    "git-branch",
    "context-used",
    "five-hour-limit",
    "weekly-limit",
    "total-input-tokens",
    "total-output-tokens",
]

[tui.model_availability_nux]
"gpt-5.5" = 4


[plugins."figma@openai-curated"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true


[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true


[marketplaces.openai-bundled]
last_updated = "2026-04-26T04:59:44Z"
source_type = "local"
source = "/Users/fengkx/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-04-24T14:33:53Z"
source_type = "local"
source = "/Users/fengkx/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[notice]
fast_default_opt_out = true
