model = "gpt-5.4"
model_reasoning_effort = "high"
personality = "pragmatic"

sandbox_mode = "workspace-write"

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"
startup_timeout_ms = 20_000


[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.weapp-devtool]
command = "npx"
args = ["@yfme/weapp-dev-mcp"]

[mcp_servers.weapp-devtool.tools.mp_ensureConnection]
approval_mode = "approve"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"


[sandbox_workspace_write]
writeable_roots = ["/Users/fengkx/Library/pnpm/store", "/Users/fengkx/.cache/uv", "/Users/fengkx/Library/Caches/Yarn/v6"]
network_access = true

[projects."/Applications/Codex.app/Contents/Resources"]
trust_level = "trusted"

[features]
multi_agent = true

[plugins."github@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true


